AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'spec/dummy_app/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/AddRuntimeDependency:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - 'lib/collection2csv/convertor.rb'
