language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head

before_install: gem install bundler

before_script:
  - cd spec/dummy_app
  - bundle exec rake db:create db:migrate
  - cd ../../


cache: bundler


gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head