language: ruby
rvm:
  - 2.0.0
  - 2.1.4
  - 2.1.5
  - 2.2.1
  - ruby-head

before_install: gem install bundler -v 1.10.6

gemfile:
  - Gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile