language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head

before_install: gem install bundler -v 1.10.6

gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile